import { notFound } from "next/navigation";
import lazyLoad from "next/dynamic";

const themeNames = [
  "abacus",
  "almanac",
  "aperture",
  "apothecary",
  "aquifer",
  "archive",
  "aurora",
  "axiom",
  "bazaar",
  "billboard",
  "blueprint",
  "brutal",
  "carbon",
  "cartouche",
  "cassette",
  "cathedral",
  "ceramic",
  "cipher",
  "circuit",
  "clockwork",
  "collage",
  "corsair",
  "cosmos",
  "darkfield",
  "darkroom",
  "darktype",
  "deco",
  "depot",
  "diorama",
  "distillery",
  "duotone",
  "earth",
  "editorial",
  "ember",
  "filament",
  "flux",
  "frost",
  "furnace",
  "gazette",
  "glass",
  "grain",
  "herbarium",
  "hologram",
  "isotope",
  "ivory",
  "kiln",
  "kinetic",
  "ledger",
  "liminal",
  "liquid",
  "lumen",
  "manuscript",
  "marquee",
  "membrane",
  "mercury",
  "midnight",
  "mosaic",
  "mycelium",
  "neo",
  "neon",
  "noir",
  "origami",
  "paper",
  "patina",
  "pavilion",
  "petroglyph",
  "phenotype",
  "polaroid",
  "prism",
  "propaganda",
  "pulse",
  "redline",
  "resin",
  "riso",
  "sediment",
  "sextant",
  "shibori",
  "signal",
  "sketch",
  "solarpunk",
  "sonar",
  "specimen",
  "stained",
  "stratum",
  "studio",
  "tableau",
  "tarot",
  "telegraph",
  "terminal",
  "terrain",
  "terrazzo",
  "tessera",
  "thermal",
  "tintype",
  "topo",
  "vapor",
  "vitrine",
  "wavelength",
  "zen",
] as const;
type ThemeName = (typeof themeNames)[number];

const themeComponents: Record<ThemeName, ReturnType<typeof lazyLoad>> = {
  abacus: lazyLoad(() => import("@/themes/abacus/ThemePage")),
  almanac: lazyLoad(() => import("@/themes/almanac/ThemePage")),
  aperture: lazyLoad(() => import("@/themes/aperture/ThemePage")),
  apothecary: lazyLoad(() => import("@/themes/apothecary/ThemePage")),
  aquifer: lazyLoad(() => import("@/themes/aquifer/ThemePage")),
  archive: lazyLoad(() => import("@/themes/archive/ThemePage")),
  aurora: lazyLoad(() => import("@/themes/aurora/ThemePage")),
  axiom: lazyLoad(() => import("@/themes/axiom/ThemePage")),
  bazaar: lazyLoad(() => import("@/themes/bazaar/ThemePage")),
  billboard: lazyLoad(() => import("@/themes/billboard/ThemePage")),
  blueprint: lazyLoad(() => import("@/themes/blueprint/ThemePage")),
  brutal: lazyLoad(() => import("@/themes/brutal/ThemePage")),
  carbon: lazyLoad(() => import("@/themes/carbon/ThemePage")),
  cartouche: lazyLoad(() => import("@/themes/cartouche/ThemePage")),
  cassette: lazyLoad(() => import("@/themes/cassette/ThemePage")),
  cathedral: lazyLoad(() => import("@/themes/cathedral/ThemePage")),
  ceramic: lazyLoad(() => import("@/themes/ceramic/ThemePage")),
  cipher: lazyLoad(() => import("@/themes/cipher/ThemePage")),
  circuit: lazyLoad(() => import("@/themes/circuit/ThemePage")),
  clockwork: lazyLoad(() => import("@/themes/clockwork/ThemePage")),
  collage: lazyLoad(() => import("@/themes/collage/ThemePage")),
  corsair: lazyLoad(() => import("@/themes/corsair/ThemePage")),
  cosmos: lazyLoad(() => import("@/themes/cosmos/ThemePage")),
  darkfield: lazyLoad(() => import("@/themes/darkfield/ThemePage")),
  darkroom: lazyLoad(() => import("@/themes/darkroom/ThemePage")),
  darktype: lazyLoad(() => import("@/themes/darktype/ThemePage")),
  deco: lazyLoad(() => import("@/themes/deco/ThemePage")),
  depot: lazyLoad(() => import("@/themes/depot/ThemePage")),
  diorama: lazyLoad(() => import("@/themes/diorama/ThemePage")),
  distillery: lazyLoad(() => import("@/themes/distillery/ThemePage")),
  duotone: lazyLoad(() => import("@/themes/duotone/ThemePage")),
  earth: lazyLoad(() => import("@/themes/earth/ThemePage")),
  editorial: lazyLoad(() => import("@/themes/editorial/ThemePage")),
  ember: lazyLoad(() => import("@/themes/ember/ThemePage")),
  filament: lazyLoad(() => import("@/themes/filament/ThemePage")),
  flux: lazyLoad(() => import("@/themes/flux/ThemePage")),
  frost: lazyLoad(() => import("@/themes/frost/ThemePage")),
  furnace: lazyLoad(() => import("@/themes/furnace/ThemePage")),
  gazette: lazyLoad(() => import("@/themes/gazette/ThemePage")),
  glass: lazyLoad(() => import("@/themes/glass/ThemePage")),
  grain: lazyLoad(() => import("@/themes/grain/ThemePage")),
  herbarium: lazyLoad(() => import("@/themes/herbarium/ThemePage")),
  hologram: lazyLoad(() => import("@/themes/hologram/ThemePage")),
  isotope: lazyLoad(() => import("@/themes/isotope/ThemePage")),
  ivory: lazyLoad(() => import("@/themes/ivory/ThemePage")),
  kiln: lazyLoad(() => import("@/themes/kiln/ThemePage")),
  kinetic: lazyLoad(() => import("@/themes/kinetic/ThemePage")),
  ledger: lazyLoad(() => import("@/themes/ledger/ThemePage")),
  liminal: lazyLoad(() => import("@/themes/liminal/ThemePage")),
  liquid: lazyLoad(() => import("@/themes/liquid/ThemePage")),
  lumen: lazyLoad(() => import("@/themes/lumen/ThemePage")),
  manuscript: lazyLoad(() => import("@/themes/manuscript/ThemePage")),
  marquee: lazyLoad(() => import("@/themes/marquee/ThemePage")),
  membrane: lazyLoad(() => import("@/themes/membrane/ThemePage")),
  mercury: lazyLoad(() => import("@/themes/mercury/ThemePage")),
  midnight: lazyLoad(() => import("@/themes/midnight/ThemePage")),
  mosaic: lazyLoad(() => import("@/themes/mosaic/ThemePage")),
  mycelium: lazyLoad(() => import("@/themes/mycelium/ThemePage")),
  neo: lazyLoad(() => import("@/themes/neo/ThemePage")),
  neon: lazyLoad(() => import("@/themes/neon/ThemePage")),
  noir: lazyLoad(() => import("@/themes/noir/ThemePage")),
  origami: lazyLoad(() => import("@/themes/origami/ThemePage")),
  paper: lazyLoad(() => import("@/themes/paper/ThemePage")),
  patina: lazyLoad(() => import("@/themes/patina/ThemePage")),
  pavilion: lazyLoad(() => import("@/themes/pavilion/ThemePage")),
  petroglyph: lazyLoad(() => import("@/themes/petroglyph/ThemePage")),
  phenotype: lazyLoad(() => import("@/themes/phenotype/ThemePage")),
  polaroid: lazyLoad(() => import("@/themes/polaroid/ThemePage")),
  prism: lazyLoad(() => import("@/themes/prism/ThemePage")),
  propaganda: lazyLoad(() => import("@/themes/propaganda/ThemePage")),
  pulse: lazyLoad(() => import("@/themes/pulse/ThemePage")),
  redline: lazyLoad(() => import("@/themes/redline/ThemePage")),
  resin: lazyLoad(() => import("@/themes/resin/ThemePage")),
  riso: lazyLoad(() => import("@/themes/riso/ThemePage")),
  sediment: lazyLoad(() => import("@/themes/sediment/ThemePage")),
  sextant: lazyLoad(() => import("@/themes/sextant/ThemePage")),
  shibori: lazyLoad(() => import("@/themes/shibori/ThemePage")),
  signal: lazyLoad(() => import("@/themes/signal/ThemePage")),
  sketch: lazyLoad(() => import("@/themes/sketch/ThemePage")),
  solarpunk: lazyLoad(() => import("@/themes/solarpunk/ThemePage")),
  sonar: lazyLoad(() => import("@/themes/sonar/ThemePage")),
  specimen: lazyLoad(() => import("@/themes/specimen/ThemePage")),
  stained: lazyLoad(() => import("@/themes/stained/ThemePage")),
  stratum: lazyLoad(() => import("@/themes/stratum/ThemePage")),
  studio: lazyLoad(() => import("@/themes/studio/ThemePage")),
  tableau: lazyLoad(() => import("@/themes/tableau/ThemePage")),
  tarot: lazyLoad(() => import("@/themes/tarot/ThemePage")),
  telegraph: lazyLoad(() => import("@/themes/telegraph/ThemePage")),
  terminal: lazyLoad(() => import("@/themes/terminal/ThemePage")),
  terrain: lazyLoad(() => import("@/themes/terrain/ThemePage")),
  terrazzo: lazyLoad(() => import("@/themes/terrazzo/ThemePage")),
  tessera: lazyLoad(() => import("@/themes/tessera/ThemePage")),
  thermal: lazyLoad(() => import("@/themes/thermal/ThemePage")),
  tintype: lazyLoad(() => import("@/themes/tintype/ThemePage")),
  topo: lazyLoad(() => import("@/themes/topo/ThemePage")),
  vapor: lazyLoad(() => import("@/themes/vapor/ThemePage")),
  vitrine: lazyLoad(() => import("@/themes/vitrine/ThemePage")),
  wavelength: lazyLoad(() => import("@/themes/wavelength/ThemePage")),
  zen: lazyLoad(() => import("@/themes/zen/ThemePage")),
};

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ theme: string }> }) {
  const { theme } = await params;
  return { title: theme.charAt(0).toUpperCase() + theme.slice(1) };
}

export default async function ThemePage({ params }: { params: Promise<{ theme: string }> }) {
  const { theme } = await params;
  const Component = themeComponents[theme as ThemeName];
  if (!Component) notFound();
  return <Component />;
}
