import { notFound } from "next/navigation";
import nextDynamic from "next/dynamic";

export const dynamic = "force-dynamic";

const themeNames = [
  "abacus",
  "almanac",
  "aperture",
  "apothecary",
  "aquifer",
  "archive",
  "aurora",
  "axiom",
  "bazaar",
  "billboard",
  "blueprint",
  "brutal",
  "carbon",
  "cartouche",
  "cassette",
  "cathedral",
  "ceramic",
  "cipher",
  "circuit",
  "clockwork",
  "collage",
  "corsair",
  "cosmos",
  "darkfield",
  "darkroom",
  "darktype",
  "deco",
  "depot",
  "diorama",
  "distillery",
  "duotone",
  "earth",
  "editorial",
  "ember",
  "filament",
  "flux",
  "frost",
  "furnace",
  "gazette",
  "glass",
  "grain",
  "herbarium",
  "hologram",
  "isotope",
  "ivory",
  "kiln",
  "kinetic",
  "ledger",
  "liminal",
  "liquid",
  "lumen",
  "manuscript",
  "marquee",
  "membrane",
  "mercury",
  "midnight",
  "mosaic",
  "mycelium",
  "neo",
  "neon",
  "noir",
  "origami",
  "paper",
  "patina",
  "pavilion",
  "petroglyph",
  "phenotype",
  "polaroid",
  "prism",
  "propaganda",
  "pulse",
  "redline",
  "resin",
  "riso",
  "sediment",
  "sextant",
  "shibori",
  "signal",
  "sketch",
  "solarpunk",
  "sonar",
  "specimen",
  "stained",
  "stratum",
  "studio",
  "tableau",
  "tarot",
  "telegraph",
  "terminal",
  "terrain",
  "terrazzo",
  "tessera",
  "thermal",
  "tintype",
  "topo",
  "vapor",
  "vitrine",
  "wavelength",
  "zen",
] as const;
type ThemeName = (typeof themeNames)[number];

const themeComponents: Record<ThemeName, ReturnType<typeof nextDynamic>> = {
  abacus: nextDynamic(() => import("@/themes/abacus/ThemePage")),
  almanac: nextDynamic(() => import("@/themes/almanac/ThemePage")),
  aperture: nextDynamic(() => import("@/themes/aperture/ThemePage")),
  apothecary: nextDynamic(() => import("@/themes/apothecary/ThemePage")),
  aquifer: nextDynamic(() => import("@/themes/aquifer/ThemePage")),
  archive: nextDynamic(() => import("@/themes/archive/ThemePage")),
  aurora: nextDynamic(() => import("@/themes/aurora/ThemePage")),
  axiom: nextDynamic(() => import("@/themes/axiom/ThemePage")),
  bazaar: nextDynamic(() => import("@/themes/bazaar/ThemePage")),
  billboard: nextDynamic(() => import("@/themes/billboard/ThemePage")),
  blueprint: nextDynamic(() => import("@/themes/blueprint/ThemePage")),
  brutal: nextDynamic(() => import("@/themes/brutal/ThemePage")),
  carbon: nextDynamic(() => import("@/themes/carbon/ThemePage")),
  cartouche: nextDynamic(() => import("@/themes/cartouche/ThemePage")),
  cassette: nextDynamic(() => import("@/themes/cassette/ThemePage")),
  cathedral: nextDynamic(() => import("@/themes/cathedral/ThemePage")),
  ceramic: nextDynamic(() => import("@/themes/ceramic/ThemePage")),
  cipher: nextDynamic(() => import("@/themes/cipher/ThemePage")),
  circuit: nextDynamic(() => import("@/themes/circuit/ThemePage")),
  clockwork: nextDynamic(() => import("@/themes/clockwork/ThemePage")),
  collage: nextDynamic(() => import("@/themes/collage/ThemePage")),
  corsair: nextDynamic(() => import("@/themes/corsair/ThemePage")),
  cosmos: nextDynamic(() => import("@/themes/cosmos/ThemePage")),
  darkfield: nextDynamic(() => import("@/themes/darkfield/ThemePage")),
  darkroom: nextDynamic(() => import("@/themes/darkroom/ThemePage")),
  darktype: nextDynamic(() => import("@/themes/darktype/ThemePage")),
  deco: nextDynamic(() => import("@/themes/deco/ThemePage")),
  depot: nextDynamic(() => import("@/themes/depot/ThemePage")),
  diorama: nextDynamic(() => import("@/themes/diorama/ThemePage")),
  distillery: nextDynamic(() => import("@/themes/distillery/ThemePage")),
  duotone: nextDynamic(() => import("@/themes/duotone/ThemePage")),
  earth: nextDynamic(() => import("@/themes/earth/ThemePage")),
  editorial: nextDynamic(() => import("@/themes/editorial/ThemePage")),
  ember: nextDynamic(() => import("@/themes/ember/ThemePage")),
  filament: nextDynamic(() => import("@/themes/filament/ThemePage")),
  flux: nextDynamic(() => import("@/themes/flux/ThemePage")),
  frost: nextDynamic(() => import("@/themes/frost/ThemePage")),
  furnace: nextDynamic(() => import("@/themes/furnace/ThemePage")),
  gazette: nextDynamic(() => import("@/themes/gazette/ThemePage")),
  glass: nextDynamic(() => import("@/themes/glass/ThemePage")),
  grain: nextDynamic(() => import("@/themes/grain/ThemePage")),
  herbarium: nextDynamic(() => import("@/themes/herbarium/ThemePage")),
  hologram: nextDynamic(() => import("@/themes/hologram/ThemePage")),
  isotope: nextDynamic(() => import("@/themes/isotope/ThemePage")),
  ivory: nextDynamic(() => import("@/themes/ivory/ThemePage")),
  kiln: nextDynamic(() => import("@/themes/kiln/ThemePage")),
  kinetic: nextDynamic(() => import("@/themes/kinetic/ThemePage")),
  ledger: nextDynamic(() => import("@/themes/ledger/ThemePage")),
  liminal: nextDynamic(() => import("@/themes/liminal/ThemePage")),
  liquid: nextDynamic(() => import("@/themes/liquid/ThemePage")),
  lumen: nextDynamic(() => import("@/themes/lumen/ThemePage")),
  manuscript: nextDynamic(() => import("@/themes/manuscript/ThemePage")),
  marquee: nextDynamic(() => import("@/themes/marquee/ThemePage")),
  membrane: nextDynamic(() => import("@/themes/membrane/ThemePage")),
  mercury: nextDynamic(() => import("@/themes/mercury/ThemePage")),
  midnight: nextDynamic(() => import("@/themes/midnight/ThemePage")),
  mosaic: nextDynamic(() => import("@/themes/mosaic/ThemePage")),
  mycelium: nextDynamic(() => import("@/themes/mycelium/ThemePage")),
  neo: nextDynamic(() => import("@/themes/neo/ThemePage")),
  neon: nextDynamic(() => import("@/themes/neon/ThemePage")),
  noir: nextDynamic(() => import("@/themes/noir/ThemePage")),
  origami: nextDynamic(() => import("@/themes/origami/ThemePage")),
  paper: nextDynamic(() => import("@/themes/paper/ThemePage")),
  patina: nextDynamic(() => import("@/themes/patina/ThemePage")),
  pavilion: nextDynamic(() => import("@/themes/pavilion/ThemePage")),
  petroglyph: nextDynamic(() => import("@/themes/petroglyph/ThemePage")),
  phenotype: nextDynamic(() => import("@/themes/phenotype/ThemePage")),
  polaroid: nextDynamic(() => import("@/themes/polaroid/ThemePage")),
  prism: nextDynamic(() => import("@/themes/prism/ThemePage")),
  propaganda: nextDynamic(() => import("@/themes/propaganda/ThemePage")),
  pulse: nextDynamic(() => import("@/themes/pulse/ThemePage")),
  redline: nextDynamic(() => import("@/themes/redline/ThemePage")),
  resin: nextDynamic(() => import("@/themes/resin/ThemePage")),
  riso: nextDynamic(() => import("@/themes/riso/ThemePage")),
  sediment: nextDynamic(() => import("@/themes/sediment/ThemePage")),
  sextant: nextDynamic(() => import("@/themes/sextant/ThemePage")),
  shibori: nextDynamic(() => import("@/themes/shibori/ThemePage")),
  signal: nextDynamic(() => import("@/themes/signal/ThemePage")),
  sketch: nextDynamic(() => import("@/themes/sketch/ThemePage")),
  solarpunk: nextDynamic(() => import("@/themes/solarpunk/ThemePage")),
  sonar: nextDynamic(() => import("@/themes/sonar/ThemePage")),
  specimen: nextDynamic(() => import("@/themes/specimen/ThemePage")),
  stained: nextDynamic(() => import("@/themes/stained/ThemePage")),
  stratum: nextDynamic(() => import("@/themes/stratum/ThemePage")),
  studio: nextDynamic(() => import("@/themes/studio/ThemePage")),
  tableau: nextDynamic(() => import("@/themes/tableau/ThemePage")),
  tarot: nextDynamic(() => import("@/themes/tarot/ThemePage")),
  telegraph: nextDynamic(() => import("@/themes/telegraph/ThemePage")),
  terminal: nextDynamic(() => import("@/themes/terminal/ThemePage")),
  terrain: nextDynamic(() => import("@/themes/terrain/ThemePage")),
  terrazzo: nextDynamic(() => import("@/themes/terrazzo/ThemePage")),
  tessera: nextDynamic(() => import("@/themes/tessera/ThemePage")),
  thermal: nextDynamic(() => import("@/themes/thermal/ThemePage")),
  tintype: nextDynamic(() => import("@/themes/tintype/ThemePage")),
  topo: nextDynamic(() => import("@/themes/topo/ThemePage")),
  vapor: nextDynamic(() => import("@/themes/vapor/ThemePage")),
  vitrine: nextDynamic(() => import("@/themes/vitrine/ThemePage")),
  wavelength: nextDynamic(() => import("@/themes/wavelength/ThemePage")),
  zen: nextDynamic(() => import("@/themes/zen/ThemePage")),
};

export default async function ThemePage({ params }: { params: Promise<{ theme: string }> }) {
  const { theme } = await params;
  const Component = themeComponents[theme as ThemeName];
  if (!Component) notFound();
  return <Component />;
}
